### ISSUE TITLE
What do the weights for Asymptotical Surprise represent? Similarity or dissimilarity?

### ISSUE THREAD

**Issue by isukrit** [CarloNicolini/paco#2]
Hi, do the weights of the edges input for Asymptotical represent the similarity between two nodes or the distance between them. I am using brain functional connectivity data for it, so should I input the direct correlation or convert it into distance? 

Thanks!

**Comment by CarloNicolini** [comment]
Hi,


The interpretation of edge weights is up to you.

If you think higher weights means higher similarity, then the resulting communities represent subsets of nodes highly similar (sum of within community edge weight is high).

If you instead provide distances (you didn't specify what kind of distances you mean, correlation distance? geometric distance?), then communities represent subsets of nodes with high distance.


In general any community detection algorithm expects similar nodes to have higher weight.



________________________________
Da: Sukrit Gupta <notifications@github.com>
Inviato: giovedì 10 maggio 2018 10:22:52
A: CarloNicolini/paco
Cc: Subscribed
Oggetto: [CarloNicolini/paco] What do the weights for Asymptotical Surprise represent? Similarity or dissimilarity? (#2)


Hi, do the weights of the edges input for Asymptotical represent the similarity between two nodes or the distance between them. I am using brain functional connectivity data for it, so should I input the direct correlation or convert it into distance?

Thanks!

-

**Comment by isukrit** [comment]
Thanks for the quick reply! :)
